In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
df = pd.read_csv("../datasets/Round1_Dataset.csv")
print("shape:", df.shape)
print("="*80)
print("\n", df.head())

shape: (500000, 24)
================================================================================

    id           f1  f2  f3        f4  ...  f19  f20       f21  f22  f23
0   0     0.000000   0   1  98615.44  ...  2.0  1.0       0.0  2.0  NaN
1   1     0.000000   0   0  21241.06  ...  3.0  2.0  163620.0  3.0  NaN
2   2  1224.690475   0   1       NaN  ...  1.0  1.0       NaN  9.0  NaN
3   3     0.000000   1   0       NaN  ...  2.0  1.0       NaN  5.0  NaN
4   4  3824.366700   0   0   7140.87  ...  3.0  1.0   68640.0  0.0  NaN

[5 rows x 24 columns]

In [18]:
features = pd.read_csv("../datasets/feature_description.csv")
print("shape:", features.shape)
print("="*80)
print("\n", features)

shape: (24, 2)
================================================================================

    Feature Name                   Feature Description
0            id                                    id
1            f1   Average Revolve Balance in last 12m
2            f2        Cancellation Calls in last 12m
3            f3  Cancellation Calls due to Collection
4            f4                Rewards Points Balance
5            f5               Total Spend in last 12m
6            f6                 Airlines Spend in 12m
7            f7                    Other Spend in 12m
8            f8            Entertainment Spend in 12m
9            f9                  Lodging Spend in 12m
10          f10                   Dining Spend in 12m
11          f11             Average Risk Score in 12m
12          f12               Login Counts to website
13          f13                   Lounge Access Count
14          f14              Credits used in airlines
15          f15                    Cab benefits usage
16          f16      Entertainment Credit Used Amount
17          f17                Total Lend Line Amount
18          f18       Total Consumer Lend Line Amount
19          f19      Number of Supplementary Accounts
20          f20          Count of Active Charge Cards
21          f21    Rewards point redeemed in 12months
22          f22          Emails Open in Last 6 months
23          f23       Emails Clicked in Last 6 months

In [ ]:
feature_map = {}

for _, row in features.iterrows():
    old_name = row['Feature Name']
    new_name = (
        row['Feature Description']
        .lower()
        .replace(" in last ", "_")
        .replace(" in ", "_")
        .replace(" ", "_")
    )
    feature_map[old_name] = new_name

df.rename(columns=feature_map, inplace=True)

In [20]:
df.head()

   id  ...  emails_clicked_6_months
0   0  ...                      NaN
1   1  ...                      NaN
2   2  ...                      NaN
3   3  ...                      NaN
4   4  ...                      NaN

[5 rows x 24 columns]

In [22]:
df.rename(columns={'cancellation_calls_due_to_collectioon': 'collection_cancellation_calls', 'login_counts_to_website':'website_login_counts', 'number_of_supplementary_accounts':'supplementary_account_count', 'count_of_active_charge_cards':'active_charge_card_count'}, inplace=True)

In [23]:
df.head()

   id  ...  emails_clicked_6_months
0   0  ...                      NaN
1   1  ...                      NaN
2   2  ...                      NaN
3   3  ...                      NaN
4   4  ...                      NaN

[5 rows x 24 columns]

In [30]:
print(df.columns)

Index(['id', 'average_revolve_balance_12m', 'cancellation_calls_12m',
       'cancellation_calls_due_to_collection', 'rewards_points_balance',
       'total_spend_12m', 'airlines_spend_12m', 'other_spend_12m',
       'entertainment_spend_12m', 'lodging_spend_12m', 'dining_spend_12m',
       'average_risk_score_12m', 'website_login_counts', 'lounge_access_count',
       'credits_used_airlines', 'cab_benefits_usage',
       'entertainment_credit_used_amount', 'total_lend_line_amount',
       'total_consumer_lend_line_amount', 'supplementary_account_count',
       'active_charge_card_count', 'rewards_point_redeemed_12months',
       'emails_open_6_months', 'emails_clicked_6_months'],
      dtype='str')

In [31]:
df.isnull().sum()

id                                           0
average_revolve_balance_12m                  0
cancellation_calls_12m                       0
cancellation_calls_due_to_collection         0
rewards_points_balance                  257228
total_spend_12m                           6340
airlines_spend_12m                      115698
other_spend_12m                         115698
entertainment_spend_12m                 115698
lodging_spend_12m                       115698
dining_spend_12m                        115698
average_risk_score_12m                    2510
website_login_counts                     25005
lounge_access_count                      13716
credits_used_airlines                    13716
cab_benefits_usage                       13716
entertainment_credit_used_amount         13716
total_lend_line_amount                  292254
total_consumer_lend_line_amount         309444
supplementary_account_count                 22
active_charge_card_count                   101
rewards_point_redeemed_12months         257228
emails_open_6_months                     94654
emails_clicked_6_months                 438965
dtype: int64

In [27]:
df.describe().T

                                         count  ...            max
id                                    500000.0  ...  499999.000000
average_revolve_balance_12m           500000.0  ...   17967.726330
cancellation_calls_12m                500000.0  ...       1.000000
cancellation_calls_due_to_collection  500000.0  ...       1.000000
rewards_points_balance                242772.0  ...  697899.350000
total_spend_12m                       493660.0  ...   13596.279900
airlines_spend_12m                    384302.0  ...   52198.432000
other_spend_12m                       384302.0  ...  146700.554000
entertainment_spend_12m               384302.0  ...    9419.874000
lodging_spend_12m                     384302.0  ...   10828.994000
dining_spend_12m                      384302.0  ...   21650.582000
average_risk_score_12m                497490.0  ...       0.326310
website_login_counts                  474995.0  ...     116.000000
lounge_access_count                   486284.0  ...       3.000000
credits_used_airlines                 486284.0  ...     200.000000
cab_benefits_usage                    486284.0  ...      11.000000
entertainment_credit_used_amount      486284.0  ...      64.403398
total_lend_line_amount                207746.0  ...   63800.000000
total_consumer_lend_line_amount       190556.0  ...   54800.000000
supplementary_account_count           499978.0  ...       4.000000
active_charge_card_count              499899.0  ...       2.000000
rewards_point_redeemed_12months       242772.0  ...  365166.150000
emails_open_6_months                  405346.0  ...      15.000000
emails_clicked_6_months                61035.0  ...       3.000000

[24 rows x 8 columns]